AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30
