Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 50
